/** The 30 Quick Draw categories of the first model. Order is the output index. */
export const LABELS = [
  "airplane",
  "apple",
  "banana",
  "bicycle",
  "bird",
  "book",
  "butterfly",
  "car",
  "cat",
  "clock",
  "cloud",
  "cup",
  "dog",
  "elephant",
  "eye",
  "fish",
  "flower",
  "guitar",
  "house",
  "key",
  "lightning",
  "moon",
  "mountain",
  "pizza",
  "rabbit",
  "star",
  "sun",
  "t-shirt",
  "tree",
  "umbrella",
] as const;
export type Label = (typeof LABELS)[number];
export const LABEL_COUNT = LABELS.length;

export const labelZh: Record<Label, string> = {
  airplane: "飞机",
  apple: "苹果",
  banana: "香蕉",
  bicycle: "自行车",
  bird: "鸟",
  book: "书",
  butterfly: "蝴蝶",
  car: "汽车",
  cat: "猫",
  clock: "时钟",
  cloud: "云",
  cup: "杯子",
  dog: "狗",
  elephant: "大象",
  eye: "眼睛",
  fish: "鱼",
  flower: "花",
  guitar: "吉他",
  house: "房子",
  key: "钥匙",
  lightning: "闪电",
  moon: "月亮",
  mountain: "山",
  pizza: "披萨",
  rabbit: "兔子",
  star: "星星",
  sun: "太阳",
  "t-shirt": "T恤",
  tree: "树",
  umbrella: "雨伞",
};
